//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariHesap
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDapertment
    {
        public int salesId { get; set; }
        public int productId { get; set; }
        public System.DateTime sellDate { get; set; }
        public int customerId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
    }
}
